[[redirects]]
from = "/information"
to = "/information"
status = 200

[[redirects]]
from = "/profile"
to = "/profile"
status = 200

[[redirects]]
from = "/contact"
to = "/contact"
status = 200

[[redirects]]
from = "/"
to = "/"
status = 200
